export const Routes = {
  home: '/',
  signIn: '/',
  signUp: '/',
  forgotPassword: '/',
  confirmEmail: '/confirm-email',

  panel: {
    verifyEmail: '/panel/verify-email',
    onboarding: '/panel/onboarding',
    notifications: '/panel/notifications',
    userSettings: '/panel/user-settings',
    security: '/panel/security',
    profile: '/panel/profile',
    referrals: '/panel/referrals',
    achievements: '/panel/achievements',
    bulletins: '/panel/bulletins',
    docs: '/panel/docs',
    help: '/panel/help',
    about: '/panel/about',

    merchant: {
      new: '/panel/merchant/new',
      onboarding: '/panel/merchant/new',
      review: '/panel/merchant/review',
      fees: '/panel/merchant/fees',
      settings: '/panel/merchant/settings',
      dashboard: '/panel/merchant/dashboard',
      liveBalance: '/panel/merchant/live-balance',
      ranking: '/panel/merchant/ranking',
      achievements: '/panel/merchant/achievements',
      transactions: '/panel/merchant/transactions',
      paymentLinks: '/panel/merchant/payment-links',
      paymentLinksNew: '/panel/merchant/payment-links/new',
      paymentLinksEdit: (id: string) => `/panel/merchant/payment-links/${id}/edit`,
      orders: '/panel/merchant/orders',
      ordersUpsert: (id: string = 'new') => `/panel/merchant/orders/upsert/${id}`,
      customers: '/panel/merchant/customers',
      customersUpsert: (id: string = 'new') => `/panel/merchant/customers/upsert/${id}`,
      products: '/panel/merchant/products',
      productsByType: (type: 'physical' | 'digital' = 'physical') => `/panel/merchant/products?type=${type}`,
      // Physical Products
      physicalProducts: '/panel/merchant/physical-products',
      physicalProductsUpsert: (id: string = 'new') => `/panel/merchant/physical-products/upsert/${id}`,
      // Digital Products
      digitalProducts: '/panel/merchant/digital-products',
      digitalProductsUpsert: (id: string = 'new') => `/panel/merchant/digital-products/upsert/${id}`,
      // Services
      services: '/panel/merchant/services',
      servicesUpsert: (id: string = 'new') => `/panel/merchant/services/upsert/${id}`,
      // Email Templates
      emailTemplates: '/panel/merchant/email-templates',
      emailTemplatesUpsert: (id: string = 'new') => `/panel/merchant/email-templates/upsert/${id}`,
      coupons: '/panel/merchant/coupons',
      couponsUpsert: (id: string = 'new') => `/panel/merchant/coupons/upsert/${id}`,
      cashouts: '/panel/merchant/cashouts',
      cashoutAccounts: '/panel/merchant/cashout-accounts',
      balanceHistory: '/panel/merchant/balance-history',
      apiCredentials: '/panel/merchant/api-credentials',
      integrations: '/panel/merchant/integrations',
      checkouts: '/panel/merchant/checkouts',
      checkoutsUpsert: (id: string = 'new') => `/panel/merchant/checkouts/upsert/${id}`,
      checkoutDetails: (id: string) => `/panel/merchant/checkouts/${id}`,
      payments: {
        creditCard: '/panel/merchant/payments/credit-card',
      },
    },

    admin: {
      dashboard: '/panel/admin/dashboard',
      balances: '/panel/admin/balances',
      referrals: '/panel/admin/referrals',
      merchants: '/panel/admin/merchants',
      merchantDetails: (id: string) => `/panel/admin/merchants/${id}`,
      merchantEvaluate: (id: string) => `/panel/admin/merchants/${id}/evaluate`,
      users: '/panel/admin/users',
      userDetails: (id: string) => `/panel/admin/users/${id}`,
      transactions: '/panel/admin/transactions',
      logs: '/panel/admin/logs',
      payouts: '/panel/admin/payouts',
      payoutDetails: (id: string) => `/panel/admin/payouts/${id}`,
      cashouts: '/panel/admin/cashouts',
      cashoutDetails: (id: string) => `/panel/admin/cashouts/${id}`,
      platformPayouts: '/panel/admin/platform-payouts',
      platformPayoutAccounts: '/panel/admin/platform-payout-accounts',
      acquirers: '/panel/admin/acquirers',
      acquirerDetails: (id: string) => `/panel/admin/acquirers/${id}`,
      templates: '/panel/admin/templates',
      templatesUpsert: (id: string = 'new') => `/panel/admin/templates/upsert/${id}`,
      platformSettings: '/panel/admin/platform-settings',
      reconciliations: '/panel/admin/reconciliations',
    },

    dev: {
      tools: '/panel/dev/tools',
    },
  },
} as const;

export type RoutePath = string;

