import type { RouteConfig } from '@/types/router';
import { RouteType } from '@/types/router';
import { UserRole, MerchantStatus, MerchantKycStatus } from '@/types/enums';
import { Routes } from './routes';

// ============================================================================
// ROTAS PÚBLICAS E SISTEMA (NÃO EXIBIDAS NO MENU)
// ============================================================================

const SYSTEM_ROUTES: RouteConfig[] = [
	{ path: Routes.home, title: 'Início', type: RouteType.Public, showInMenu: false },
	{ path: Routes.confirmEmail, title: 'Confirmar Email', type: RouteType.Open, showInMenu: false },
	{
		path: Routes.panel.verifyEmail,
		title: 'Verificar Email',
		type: RouteType.Private,
		access: { requiresEmailVerified: false },
		showInMenu: false,
	},
	{
		path: Routes.panel.onboarding,
		title: 'Onboarding',
		type: RouteType.Private,
		showInMenu: false,
	},
	{ path: Routes.panel.merchant.new, title: 'Criar Organização', type: RouteType.Private, showInMenu: false },
];

// ============================================================================
// ROTAS DO MERCHANT (ORGANIZADAS POR MACRO-FLUXOS)
// ============================================================================

const MERCHANT_ROUTES: RouteConfig[] = [
	// --- SEÇÃO: GESTÃO DE VENDAS ---
	{
		path: Routes.panel.merchant.dashboard,
		title: 'Dashboard',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'GraphNewUp',
		menuSection: 'Vendas',
		menuOrder: 1,
		showInMenu: true,
	},
	{
		path: Routes.panel.merchant.orders,
		title: 'Pedidos',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'ShoppingCartCheck01Icon',
		menuSection: 'Vendas',
		menuOrder: 2,
		showInMenu: true,
	},
	{
		path: Routes.panel.merchant.products,
		title: 'Produtos',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'BoxMinimalistic',
		menuSection: 'Vendas',
		menuOrder: 3,
		showInMenu: true,
	},
	{
		path: Routes.panel.merchant.physicalProducts,
		title: 'Produtos Físicos',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'BoxMinimalistic',
		menuSection: 'Vendas',
		menuOrder: 3,
		showInMenu: false,
	},
	{
		path: Routes.panel.merchant.digitalProducts,
		title: 'Produtos Digitais',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'DigitalProduct',
		menuSection: 'Vendas',
		menuOrder: 4,
		showInMenu: false,
	},
	{
		path: Routes.panel.merchant.services,
		title: 'Serviços',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'Service',
		menuSection: 'Vendas',
		menuOrder: 4,
		showInMenu: true,
	},
	{
		path: Routes.panel.merchant.checkouts,
		title: 'Checkouts',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'ShoppingBasket01Icon',
		menuSection: 'Vendas',
		menuOrder: 5,
		showInMenu: true,
	},
	{
		path: Routes.panel.merchant.customers,
		title: 'Clientes',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'UsersGroupTwoRounded',
		menuSection: 'Vendas',
		menuOrder: 6,
		showInMenu: true,
	},
	{
		path: Routes.panel.merchant.coupons,
		title: 'Cupons',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'Coupon',
		menuSection: 'Vendas',
		menuOrder: 7,
		showInMenu: true,
	},
	{
		path: Routes.panel.merchant.ranking,
		title: 'Ranking',
		type: RouteType.Private,
		iconName: 'ChampionIcon',
		menuSection: 'Vendas',
		menuOrder: 8,
		showInMenu: true,
		badgeColor: 'warning',
		badgeText: 'Novo',
		sidebarEffect: 'gold-reflection',
	},
	{
		path: Routes.panel.merchant.achievements,
		title: 'Conquistas',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'StarAward02Icon',
		menuSection: 'Vendas',
		menuOrder: 9,
		showInMenu: false,
	},
	{
		path: Routes.panel.achievements,
		title: 'Conquistas',
		type: RouteType.Private,
		access: {},
		iconName: 'StarAward02Icon',
		showInMenu: false,
	},
	{
		path: Routes.panel.merchant.emailTemplates,
		title: 'E-mails',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'EmailTemplate',
		menuSection: 'Configurações',
		menuOrder: 3,
		showInMenu: false,
	},

	// --- SEÇÃO: FINANCEIRO ---
	{
		path: Routes.panel.merchant.transactions,
		title: 'Transações',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'ChartSquare',
		menuSection: 'Financeiro',
		menuOrder: 1,
		showInMenu: true,
	},
	{
		path: Routes.panel.merchant.paymentLinks,
		title: 'Link de pagamento',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'Link02Icon',
		menuSection: 'Financeiro',
		menuOrder: 2,
		showInMenu: true,
		badgeColor: 'warning',
		badgeText: 'Novo',
	},
	{
		path: Routes.panel.merchant.cashouts,
		title: 'Saques',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'MoneyBag',
		menuSection: 'Financeiro',
		menuOrder: 3,
		showInMenu: true,
	},
	{
		path: Routes.panel.merchant.cashoutAccounts,
		title: 'Contas de Saque',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'Banknote',
		menuSection: 'Financeiro',
		menuOrder: 4,
		showInMenu: false,
	},
	{
		path: Routes.panel.merchant.balanceHistory,
		title: 'Histórico de Saldo',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'History',
		menuSection: 'Financeiro',
		menuOrder: 4,
		showInMenu: true,
	},

	// --- SEÇÃO: CONFIGURAÇÕES E CONTA ---
	{
		path: Routes.panel.merchant.review,
		title: 'Meu Cadastro',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Draft, MerchantStatus.Active, MerchantStatus.Suspended, MerchantStatus.Inactive],
			merchantKycStatus: [
				MerchantKycStatus.Pending,
				MerchantKycStatus.UnderReview,
				MerchantKycStatus.Complement,
				MerchantKycStatus.Rejected,
				MerchantKycStatus.Approved,
			],
		},
		redirectTo: Routes.panel.merchant.onboarding,
		iconName: 'ClipboardText',
		menuSection: 'Configurações',
		menuOrder: 1,
		showInMenu: true,
	},
	{
		path: Routes.panel.merchant.onboarding,
		title: 'Completar Cadastro',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Draft, MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Draft, MerchantKycStatus.Complement],
		},
		redirectTo: Routes.panel.merchant.new,
		iconName: 'ClipboardText',
		menuSection: 'Configurações',
		menuOrder: 1,
		showInMenu: true,
	},
	{
		path: Routes.panel.merchant.apiCredentials,
		title: 'Credenciais de API',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'Key',
		menuSection: 'Configurações',
		menuOrder: 2,
		showInMenu: true,
	},
	{
		path: Routes.panel.merchant.fees,
		title: 'Taxas e Limites',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'FeesAndLimits',
		menuSection: 'Configurações',
		menuOrder: 4,
		showInMenu: true,
	},
	{
		path: Routes.panel.merchant.integrations,
		title: 'Integrações',
		type: RouteType.Private,
		access: {
			requiresMerchant: true,
			merchantStatus: [MerchantStatus.Active],
			merchantKycStatus: [MerchantKycStatus.Approved],
		},
		redirectTo: Routes.panel.merchant.review,
		iconName: 'PuzzleIcon',
		menuSection: 'Configurações',
		menuOrder: 5,
		badgeColor: 'warning',
		badgeText: 'Novo',
		showInMenu: true,
	},
	{
		path: Routes.panel.merchant.settings,
		title: 'Configurações',
		type: RouteType.Private,
		access: { requiresMerchant: true, merchantStatus: [MerchantStatus.Active, MerchantStatus.Draft] },
		redirectTo: Routes.panel.merchant.review,
		iconName: 'Settings',
		menuSection: 'Configurações',
		menuOrder: 5,
		showInMenu: true,
	},
];

// ============================================================================
// ADMINISTRAÇÃO E SUPORTE
// ============================================================================

const ADMIN_ROUTES: RouteConfig[] = [
	{
		path: Routes.panel.admin.dashboard,
		title: 'Dashboard',
		type: RouteType.Private,
		access: { roles: [UserRole.Admin, UserRole.God] },
		iconName: 'GraphNewUp',
		menuSection: 'Administração',
		menuOrder: 1,
		showInMenu: true,
	},
	{
		path: Routes.panel.admin.balances,
		title: 'Saldos',
		type: RouteType.Private,
		access: { roles: [UserRole.Admin, UserRole.God] },
		iconName: 'Banknote',
		menuSection: 'Administração',
		menuOrder: 3,
		showInMenu: true,
	},
	{
		path: Routes.panel.admin.merchants,
		title: 'Organizações',
		type: RouteType.Private,
		access: { roles: [UserRole.Admin, UserRole.God] },
		iconName: 'Buildings',
		menuSection: 'Administração',
		menuOrder: 4,
		showInMenu: true,
	},
	{
		path: Routes.panel.admin.users,
		title: 'Usuários',
		type: RouteType.Private,
		access: { roles: [UserRole.Admin, UserRole.God] },
		iconName: 'UsersGroupTwoRounded',
		menuSection: 'Administração',
		menuOrder: 5,
		showInMenu: true,
	},
	{
		path: Routes.panel.admin.referrals,
		title: 'Saque das indicações',
		type: RouteType.Private,
		access: { roles: [UserRole.Admin, UserRole.God] },
		iconName: 'Target02Icon',
		menuSection: 'Administração',
		menuOrder: 6,
		showInMenu: true,
	},
	{
		path: Routes.panel.admin.transactions,
		title: 'Transações',
		type: RouteType.Private,
		access: { roles: [UserRole.Admin, UserRole.God] },
		iconName: 'ChartSquare',
		menuSection: 'Administração',
		menuOrder: 7,
		showInMenu: true,
	},
	{
		path: Routes.panel.admin.logs,
		title: 'Logs',
		type: RouteType.Private,
		access: { roles: [UserRole.Admin, UserRole.God] },
		iconName: 'DocumentText',
		menuSection: 'Administração',
		menuOrder: 99,
		showInMenu: true,
	},
	{
		path: Routes.panel.admin.payouts,
		title: 'Saques de Organizações',
		type: RouteType.Private,
		access: { roles: [UserRole.Admin, UserRole.God] },
		iconName: 'MoneyBag',
		menuSection: 'Administração',
		menuOrder: 8,
		showInMenu: true,
	},
	{
		path: Routes.panel.admin.platformPayouts,
		title: 'Saques da Plataforma',
		type: RouteType.Private,
		access: { roles: [UserRole.Admin, UserRole.God] },
		iconName: 'WalletMoney',
		menuSection: 'Administração',
		menuOrder: 9,
		showInMenu: true,
	},
	{
		path: Routes.panel.admin.platformPayoutAccounts,
		title: 'Contas de Saque (Plataforma)',
		type: RouteType.Private,
		access: { roles: [UserRole.God] },
		iconName: 'Banknote',
		menuSection: 'Administração',
		menuOrder: 10,
		showInMenu: false,
	},
	{
		path: Routes.panel.admin.acquirers,
		title: 'Processadoras',
		type: RouteType.Private,
		access: { roles: [UserRole.Admin, UserRole.God] },
		iconName: 'Server',
		menuSection: 'Administração',
		menuOrder: 11,
		showInMenu: true,
	},
	{
		path: Routes.panel.admin.templates,
		title: 'Checkouts',
		type: RouteType.Private,
		access: {
			roles: [UserRole.Admin, UserRole.God],
		},
		redirectTo: Routes.panel.merchant.dashboard,
		iconName: 'WidgetAdd',
		menuSection: 'Administração',
		menuOrder: 12,
		showInMenu: true,
	},
	{
		path: Routes.panel.admin.reconciliations,
		title: 'Reconciliações',
		type: RouteType.Private,
		access: { roles: [UserRole.Admin, UserRole.God] },
		iconName: 'Reconciliations',
		menuSection: 'Administração',
		menuOrder: 14,
		showInMenu: true,
	},
	{
		path: Routes.panel.admin.platformSettings,
		title: 'Configurações',
		type: RouteType.Private,
		access: { roles: [UserRole.Admin, UserRole.God] },
		iconName: 'Settings',
		menuSection: 'Administração',
		menuOrder: 15,
		showInMenu: true,
	},
	{
		path: Routes.panel.dev.tools,
		title: 'Dev Tools',
		type: RouteType.Private,
		access: { roles: [UserRole.God] },
		iconName: 'CodeSquare',
		menuSection: 'Sistema',
		menuOrder: 1,
		showInMenu: true,
	},
];

const SUPPORT_ROUTES: RouteConfig[] = [
	{
		path: Routes.panel.referrals,
		title: 'Indique e Ganhe',
		type: RouteType.Private,
		iconName: 'UsersGroupTwoRounded',
		menuSection: 'Suporte',
		menuOrder: 2,
		showInMenu: false,
	},
	{
		path: Routes.panel.bulletins,
		title: 'Informativos',
		type: RouteType.Private,
		iconName: 'News01Icon',
		menuSection: 'Suporte',
		menuOrder: 1,
		showInMenu: true,
	},
	{
		path: Routes.panel.docs,
		title: 'Documentação',
		type: RouteType.Private,
		iconName: 'DocumentText',
		menuSection: 'Suporte',
		menuOrder: 3,
		isExternal: true,
		showInMenu: false,
	},
	{
		path: Routes.panel.help,
		title: 'Central de Ajuda',
		type: RouteType.Private,
		iconName: 'QuestionCircle',
		menuSection: 'Suporte',
		menuOrder: 4,
		showInMenu: true,
	},
];

// ============================================================================
// EXPORTAÇÃO FINAL
// ============================================================================

export const ROUTES_CONFIG: RouteConfig[] = [...SYSTEM_ROUTES, ...MERCHANT_ROUTES, ...ADMIN_ROUTES, ...SUPPORT_ROUTES];

export const MENU_SECTIONS_ORDER = ['Administração', 'Vendas', 'Financeiro', 'Configurações', 'Suporte', 'Sistema'];
